import {
  BossTypes,
  BossWaveConfig,
  DropItemType,
  EnemyConfig,
  MobTypes,
  MobWaveConfig,
} from "../Types";

export const BOSS_DEPTH = 100;
export const ORB_DEPTH = 70;

// XP values for each drop item type
export const DROP_ITEM_XP_VALUES: Record<DropItemType, number> = {
  blueOrb: 5,
  greenOrb: 12,
  grayOrb: 26,
  yellowOrb: 65,
  purpleOrb: 125,
};

// Score thresholds for boss spawns
export const BOSS_WAVE_THRESHOLDS: BossWaveConfig[] = [
  { triggerAt: 30, bossType: "boss1", totalEnemy: 1, flag: "bossWave1" },
  { triggerAt: 60, bossType: "boss2", totalEnemy: 1, flag: "bossWave2" },
  { triggerAt: 90, bossType: "boss3", totalEnemy: 1, flag: "bossWave3" },
  { triggerAt: 120, bossType: "boss1", totalEnemy: 2, flag: "bossWave4" },
  { triggerAt: 150, bossType: "boss2", totalEnemy: 2, flag: "bossWave5" },
  { triggerAt: 180, bossType: "boss3", totalEnemy: 2, flag: "bossWave6" },

  { triggerAt: 210, bossType: "boss1", totalEnemy: 1, flag: "bossWave7_a" },
  { triggerAt: 210, bossType: "boss2", totalEnemy: 1, flag: "bossWave7_b" },

  { triggerAt: 240, bossType: "boss2", totalEnemy: 2, flag: "bossWave8_a" },
  { triggerAt: 240, bossType: "boss3", totalEnemy: 1, flag: "bossWave8_b" },

  { triggerAt: 270, bossType: "boss1", totalEnemy: 2, flag: "bossWave9_a" },
  { triggerAt: 270, bossType: "boss3", totalEnemy: 2, flag: "bossWave9_b" },

  { triggerAt: 275, bossType: "boss2", totalEnemy: 4, flag: "bossWave10_a" },
  { triggerAt: 275, bossType: "boss3", totalEnemy: 4, flag: "bossWave10_b" },

  { triggerAt: 280, bossType: "boss1", totalEnemy: 10, flag: "bossWave11_a" },
  { triggerAt: 280, bossType: "boss2", totalEnemy: 5, flag: "bossWave11_b" },
  { triggerAt: 280, bossType: "boss3", totalEnemy: 3, flag: "bossWave11_c" },

  { triggerAt: 285, bossType: "boss1", totalEnemy: 10, flag: "bossWave12_a" },
  { triggerAt: 285, bossType: "boss2", totalEnemy: 7, flag: "bossWave12_b" },
  { triggerAt: 285, bossType: "boss3", totalEnemy: 3, flag: "bossWave12_c" },

  { triggerAt: 290, bossType: "boss1", totalEnemy: 10, flag: "bossWave13_a" },
  { triggerAt: 290, bossType: "boss2", totalEnemy: 10, flag: "bossWave13_b" },
  { triggerAt: 290, bossType: "boss3", totalEnemy: 10, flag: "bossWave13_c" },
];

// Score thresholds for mob spawn
export const MOB_WAVE_THRESHOLDS: MobWaveConfig[] = [
  {
    triggerAt: 0,
    mobType: "mob1",
    totalEnemy: 40,
    batchSize: 2,
    delay: 2000,
    flag: "wave1",
  },
  {
    triggerAt: 30,
    mobType: "mob2",
    totalEnemy: 60,
    batchSize: 3,
    delay: 1800,
    flag: "wave2",
  },
  {
    triggerAt: 60,
    mobType: "mob1",
    totalEnemy: 70,
    batchSize: 3,
    delay: 1400,
    flag: "wave3",
  },
  {
    triggerAt: 90,
    mobType: "mob3",
    totalEnemy: 85,
    batchSize: 4,
    delay: 1200,
    flag: "wave4",
  },
  {
    triggerAt: 120,
    mobType: "mob2",
    totalEnemy: 110,
    batchSize: 4,
    delay: 1000,
    flag: "wave5",
  },
  {
    triggerAt: 150,
    mobType: "mob4",
    totalEnemy: 110,
    batchSize: 4,
    delay: 900,
    flag: "wave6",
  },
  {
    triggerAt: 180,
    mobType: "mob3",
    totalEnemy: 180,
    batchSize: 5,
    delay: 800,
    flag: "wave7",
  },
  {
    triggerAt: 210,
    mobType: "mob4",
    totalEnemy: 150,
    batchSize: 6,
    delay: 800,
    flag: "wave8",
  },
  {
    triggerAt: 240,
    mobType: "mob5",
    totalEnemy: 180,
    batchSize: 7,
    delay: 700,
    flag: "wave9",
  },
  // Endless
  {
    triggerAt: 290,
    mobType: "mob1",
    totalEnemy: 100,
    batchSize: 3,
    delay: 2500,
    flag: "endless",
  },
  {
    triggerAt: 290,
    mobType: "mob2",
    totalEnemy: 120,
    batchSize: 3,
    delay: 2200,
    flag: "endless",
  },
  {
    triggerAt: 290,
    mobType: "mob3",
    totalEnemy: 150,
    batchSize: 4,
    delay: 1290,
    flag: "endless",
  },
  {
    triggerAt: 290,
    mobType: "mob4",
    totalEnemy: 180,
    batchSize: 4,
    delay: 1400,
    flag: "endless",
  },
  {
    triggerAt: 290,
    mobType: "mob5",
    totalEnemy: 250,
    batchSize: 5,
    delay: 1000,
    flag: "endless",
  },
];

// Balance enemy stats
export const ENEMY_BALANCE_STATS = {
  mob1: { HP: 4, SPEED: 20, DAMAGE: 1 },
  mob2: { HP: 8, SPEED: 25, DAMAGE: 3 },
  mob3: { HP: 15, SPEED: 30, DAMAGE: 5 },
  mob4: { HP: 30, SPEED: 20, DAMAGE: 7 },
  mob5: { HP: 50, SPEED: 35, DAMAGE: 10 },

  boss1: { HP: 150, SPEED: 25, DAMAGE: 10 },
  boss2: { HP: 350, SPEED: 30, DAMAGE: 12 },
  boss3: { HP: 600, SPEED: 30, DAMAGE: 15 },
} as const;

// Mob configurations
export const MOB_CONFIGS: Record<MobTypes, EnemyConfig> = {
  mob1: {
    key: "Mob1",
    scale: 0.8,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: 80,
    speed: ENEMY_BALANCE_STATS.mob1.SPEED,
    hp: ENEMY_BALANCE_STATS.mob1.HP,
    maxHp: ENEMY_BALANCE_STATS.mob1.HP,
    dropItem: "blueOrb",
  },
  mob2: {
    key: "Mob2",
    scale: 0.8,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: -8,
    offsetY: -12,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: 85,
    speed: ENEMY_BALANCE_STATS.mob2.SPEED,
    hp: ENEMY_BALANCE_STATS.mob2.HP,
    maxHp: ENEMY_BALANCE_STATS.mob2.HP,
    dropItem: "blueOrb",
  },
  mob3: {
    key: "Mob3",
    scale: 0.8,
    bodyWidth: 18,
    bodyHeight: 18,
    offsetX: -9,
    offsetY: -9,
    frameStart: 0,
    frameEnd: 12,
    frameRate: 10,
    depth: 80,
    speed: ENEMY_BALANCE_STATS.mob3.SPEED,
    hp: ENEMY_BALANCE_STATS.mob3.HP,
    maxHp: ENEMY_BALANCE_STATS.mob3.HP,
    dropItem: "greenOrb",
  },
  mob4: {
    key: "Mob4",
    scale: 0.8,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 11,
    frameRate: 10,
    depth: 80,
    speed: ENEMY_BALANCE_STATS.mob4.SPEED,
    hp: ENEMY_BALANCE_STATS.mob4.HP,
    maxHp: ENEMY_BALANCE_STATS.mob4.HP,
    dropItem: "grayOrb",
  },
  mob5: {
    key: "Mob5",
    scale: 0.8,
    bodyWidth: 16,
    bodyHeight: 32,
    offsetX: -8,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 4,
    frameRate: 5,
    depth: 90,
    speed: ENEMY_BALANCE_STATS.mob5.SPEED,
    hp: ENEMY_BALANCE_STATS.mob5.HP,
    maxHp: ENEMY_BALANCE_STATS.mob5.HP,
    dropItem: "grayOrb",
  },
};

// Boss enemy configurations
export const BOSS_CONFIGS: Record<BossTypes, EnemyConfig> = {
  boss1: {
    key: "Boss1",
    scale: 0.8,
    bodyWidth: 55,
    bodyHeight: 68,
    offsetX: -27.5,
    offsetY: -34,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: 100,
    speed: ENEMY_BALANCE_STATS.boss1.SPEED,
    hp: ENEMY_BALANCE_STATS.boss1.HP,
    maxHp: ENEMY_BALANCE_STATS.boss1.HP,
    dropItem: "yellowOrb",
  },
  boss2: {
    key: "Boss2",
    scale: 0.8,
    bodyWidth: 58,
    bodyHeight: 56,
    offsetX: -28,
    offsetY: -28,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.boss2.SPEED,
    hp: ENEMY_BALANCE_STATS.boss2.HP,
    maxHp: ENEMY_BALANCE_STATS.boss2.HP,
    dropItem: "purpleOrb",
  },
  boss3: {
    key: "Boss3",
    scale: 0.8,
    bodyWidth: 50,
    bodyHeight: 55,
    offsetX: -25,
    offsetY: -27.5,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.boss3.SPEED,
    hp: ENEMY_BALANCE_STATS.boss3.HP,
    maxHp: ENEMY_BALANCE_STATS.boss3.HP,
    dropItem: "purpleOrb",
  },
};
